### PR TITLE
mosart1.1.07: Fix Nag compiler error, a few small changes, and convert ChangeLog to markdown

### LINKED ISSUE #110: mosart1.1.06 fails on compile with Nag compiler on Izumi
@fischer-ncar found this in testing of cesm3_0_alpha05c. Nag compiler fails to compile for mosart1.1.06. We had problems with Izumi, so I purposefully didn't make baselines on Izumi. I had done some testing so thought I had pushed the fix for this, but obviously didn't.

### LINKED ISSUE #111: Move ChangeLog file to markdown format
I did this in the RTM changelog and we plan to do it in the CTSM change files as well. But, we will change the ChangeLog file into markdown format so that we can take advantage of the syntax highlighting and github linking that is available. 

The CTSM issue is here:

https://github.com/ESCOMP/CTSM/issues/2766

### PR DESCRIPTION
**Pull request by ekluzek**
Fixes to work with the nag compiler, a few small changes to time-manager for what is being put into CTSM and already put into RTM. Also moves the changelog file to markdown format.

Fixes #110 
Fixes #111

### CODE REVIEW

File: src/riverroute/mosart_restfile.F90 [hunk 1]
```diff
@@ -248,7 +248,7 @@ subroutine restFile_read_pfile( pnamer )
 
       if (mainproc) then
          call get_curr_date(yr, mon, day, tod)
-         write(timestamp,'(".",i4.4,"-",i2.2,"-",i2.2,"-",i5.5)'),yr,mon,day,tod
+         write(timestamp,'(".",i4.4,"-",i2.2,"-",i2.2,"-",i5.5)') yr,mon,day,tod
```
Comment (slevis-lmwg) [inline src/riverroute/mosart_restfile.F90:251]: I assume this is the bug-fix. The rest changes the ChangeLog.

Approving.

@ekluzek I forgot to wait for this mosart tag and already started aux_clm in #2838 pointing to mosart1.1.06 and rtm1_0_84. Should I stop and wait for this? I'm guessing not, but maybe I should wait before starting the mosart test-suite, yes?

**Review by slevis-lmwg — APPROVED** [review]
One comment/question. Approving.

File: src/riverroute/mosart_restfile.F90 (hunk 1 above)
Comment (ekluzek) [reply src/riverroute/mosart_restfile.F90:251]: @slevis-lmwg actually ESCOMP/CTSM#2828 is using the older mosart/rtm tags since we are coordinating the same behavior updates with each of the three PR's. So you'll be using the existing mosart/rtm tags for those three, and we'll do another update after those to bring in the very latest mosart/rtm tags with the rpointer update. So your testing you've started is perfectly fine.

That's issue ESCOMP/CTSM#2923 to do the update to the rpointer mosart/rtm tags. That's something we can do on b4b-dev.
